### ISSUE TITLE
add defaultValue and value props support for some form like components

### ISSUE THREAD

**Issue by beizhedenglong** [React95/React95#100]
add `defaultValue` and `value` props support for some `form like ` components so that we can control the components switch between controlled and uncontrolled. it was used by some popular UI library like [`Material UI`](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/internal/SwitchBase.js#L57) and `antd`.  I have written a tiny module ([rc-value](https://github.com/beizhedenglong/rc-value)) to illustrate this pattern.

**Comment by ggdaltoso** [comment]
I guess I already fixed this. Our Input component, for example, is just a `forwardRef` if an `input`, in the end:

```jsx
export const Input = forwardRef<HTMLInputElement, InputProps>((rest, ref) => (
  <Frame {...rest} ref={ref} className={input} as="input" />
));
```

I'm going to close this but feel free to reopen it if needed, @beizhedenglong 

Thanks for opening this issue on Nov 2022, and sorry for taking that long to answer you back 🕊
