### ISSUE TITLE
Enabling style overrides via styled-components

### ISSUE THREAD

**Issue by anton-g** [React95/React95#109]
Hi!

Right now it's impossible to apply custom styling to components with styled-components since the components don't pass down the `className`-prop.
For example, for the Button-component the fix would be that this:
```
const Button = ({ children, value, onClick }) => (
  <Btn value={value || children} onClick={onClick}>
    {children || value}
  </Btn>
)
```
becomes this:
```
const Button = ({ children, value, onClick, className }) => (
  <Btn value={value || children} onClick={onClick} className={className}>
    {children || value}
  </Btn>
)
```

I'd be happy to submit a PR, but wanted to run it by you first.

**Comment by ggdaltoso** [comment]
Hi @anton-g!

Would be better if it was like this?
```const Button = ({ children, value, onClick, ...props}) => (
  <Btn value={value || children} onClick={onClick} {...props}>
    {children || value}
  </Btn>
)```

What do you think?
🤔

**Comment by anton-g** [comment]
Yep, that sounds like a better way to do it! I'll create a PR if I get some time over!
