### ISSUE TITLE
Disabled-checked radio-button looks like disabled-unchecked

### ISSUE THREAD

**Issue by mikegsrv** [React95/React95#111]
Hello! 

I was surfing through the https://react95.github.io/React95 and it seems to be issue with disabled-checked radio button: it looks the same as disabled-unchecked.

**Steps to reproduce:**
Prerequisites: macOS High Sierra 10.13.5 + Google Chrome Canary 77.0.3842.0
Go to: https://react95.github.io/React95 > RadioButton

**Actual Result**
![Screen Shot 2019-07-04 at 11 26 47](https://user-images.githubusercontent.com/15021175/60651354-b43c5000-9e4e-11e9-976a-f097e7e74ebc.png)

Last radio marked as unchecked and disabled.

**Expected Result**
Last radio marked as checked and disabled.

**Brief analysis**
The problem connected with “background-image” CSS property of RadioButton. Unfortunately, I had no time to reverse the sources, but I’m sure, that the code works well except [one line](https://github.com/React95/React95/blob/9aad7de8c6da43b5b095c970618e9cc990eee7b2/components/RadioButton/RadioButton.jsx#L53). After fixing I propose to add some tests to this behavior, but currently I’m not able to propose any.
 
If there’s any chance I can assist in reproducing / debugging / fixing – feel free to contact me.

Thanks for the library! Awesome!

Best regards,
Mikhail

**Comment by ggdaltoso** [comment]
Wow! What a detailed issue!

Thanks for that @mikegsrv!

Well, it seems you have found where this could be fixed. 
You sure you don't open a PR for it? I could do it but it would be nice if you collaborate with this project.

**Comment by mikegsrv** [comment]
Sorry for the delay in aswer.
Sure, will do in a day or two! Need some time to investigate how it's working and what exactly led to an error as at first sight everything seems normal.
