### ISSUE TITLE
what happened to the documentation?

### ISSUE THREAD

**Issue by samirsd** [React95/React95#127]
there used to be avatars in the storybook with helpful code snippet now i don't see them and i don't see any sign of documentation

**Comment by ggdaltoso** [comment]
Are you talking about clippy?

**Comment by samirsd** [comment]
Yes

**Comment by ggdaltoso** [comment]
After updating the storybook to v5, we have some struggles with our custom decorator used to perform the Clippy animation and interaction.

We have [plans to build a better doc experience](https://github.com/React95/React95/issues/33), maybe using Gatsby, and to make Clippy live again.

Want to contribute with it?

**Comment by samirsd** [comment]
I think the documentation quality was more than adequate before so I would just try to roll it back to when clippy worked.

**Comment by ggdaltoso** [comment]
We are working on something better than Storybook. You can see the progress at [explorer](https://github.com/React95/React95/tree/explorer) branch.

I'll close this issue but if you are interested, please, contribute! It would be nice!
