### ISSUE TITLE
Checkboxes don't pass styles through

### ISSUE THREAD

**Issue by DanielRosenwasser** [React95/React95#129]
If I try to render a checkbox in the following way:

```tsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import { Checkbox } from "@react95/core";

let style = {
    left: "200px",
    top: "200px",
    position: "relative"
};

ReactDOM.render(
    <div>
        <Checkbox style={style} />
    </div>,
    document.getElementById("app"),
);
```

relative positioning isn't respected. In contrast, using `Button`, styles are preserved.

```tsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import { Button } from "@react95/core";

let style = {
    left: "200px",
    top: "200px",
    position: "relative"
};

ReactDOM.render(
    <div>
        <Button style={style} />
    </div>,
    document.getElementById("app"),
);
```

**Comment by ggdaltoso** [comment]
Hi, @DanielRosenwasser 

Thank you for opening this issue!

It seems to have a simple solution. Diving through the [Checkbox code](https://github.com/React95/React95/blob/master/packages/core/components/Checkbox/Checkbox.jsx#L98) I found the problem: 

```diff
- <Label {...style} checked={checked} disabled={disabled}>
+ <Label style={style} checked={checked} disabled={disabled}>
```

Would you like to open a PR solving this? I would appreciate it if you could!

Thanks!

**Comment by DanielRosenwasser** [comment]
Thanks for the tip! I just sent a PR at #130.
