### ISSUE TITLE
Create showcase area in README.md

### ISSUE THREAD

**Issue by kaiofelipejs** [React95/React95#148]
This idea came from @ggdaltoso [on Twitter](https://twitter.com/ggdaltoso/status/1267951868828942337).

The purpose is show to other developers cases of apps and websites that use the React95 library.

**Comment by ggdaltoso** [comment]
This is awesome!

I think it would fit nicely between "Development" and "Contributors" sections, named "Awesome projects", as a simple URL list. 

What do you think?

**Comment by AGreenObject** [comment]
I think this is really needed! I've often found myself scouring the web for examples of how React95 is used

**Comment by kaiofelipejs** [comment]
I like this idea @ggdaltoso, standardized, and simple.

**Comment by allyssonsantos** [comment]
@ggdaltoso I think this is a great idea too.
Maybe we can put a folder with all the projects in the explorer that we are building too. 😆

**Comment by ggdaltoso** [comment]
@allyssonsantos 
And if we add an iframe with 95 IE view in the explorer?

I could imagine...

![image](https://user-images.githubusercontent.com/6536985/83757970-ab985f00-a647-11ea-9f3c-4bee1d5d9eb7.png)

**Comment by allyssonsantos** [comment]
@ggdaltoso Hahahahaha, An Internet Explorer window with the project loading at the iframe ❤️ great idea!

**Comment by ggdaltoso** [comment]
@kaiofelipejs 
Just you to know, I've add the "Awesome Projects" section in the root README.md file (see #149). As soon as you like, you could open a PR adding yours.

**Comment by kaiofelipejs** [comment]
@ggdaltoso 
Awesome! Thanks for your agility. Soon I will put my project there.

**Comment by ggdaltoso** [comment]
@InsafKhamzin @LRNZ09 
Pinging you guys to let you know about this. Feel free to open a PR with your awesome projects too.

🚀

**Comment by LRNZ09** [comment]
Sure thing! I'll do it soon @ggdaltoso

**Comment by InsafKhamzin** [comment]
> 
> 
> @InsafKhamzin @LRNZ09
> Pinging you guys to let you know about this. Feel free to open a PR with your awesome projects too.
> 
> 🚀

Done! @ggdaltoso
