### ISSUE TITLE
Alert is appearing in TaskBar

### ISSUE THREAD

**Issue by ggdaltoso** [React95/React95#155]
![image](https://user-images.githubusercontent.com/6536985/83901166-b2e76780-a730-11ea-9f80-31684c4fe0cb.png)

As we can saw in this image, the Alert component is appearing in TaskBar when it shouldn't. 

Also, the close Button seems to be not clickable, in the real Alert.
![image](https://user-images.githubusercontent.com/6536985/83901406-1a051c00-a731-11ea-8d30-fad541c57b90.png)

We could handle this with the prop `onClose` in the Modal component (it there is none, don't show the Modal inside TaskBar), changing the Modal component and, consequently, reflecting in the Alert or the Alert should not use Modal on its own render. 

What is the best approach?

**Comment by sparky-raccoon** [comment]
Hello there ! Can I take care of this ?
I'd rather go with the first solution ✨

**Comment by ggdaltoso** [comment]
Of course!

You can easily find me on [Gitter](https://gitter.im/React95/React95) if you need help!
