### ISSUE TITLE
Wrong font

### ISSUE THREAD

**Issue by ggdaltoso** [React95/React95#158]
As we can easily see in [95Recipes](https://ggdaltoso.dev/95Recipes/) the font family provided from React95 is not the right one, since it does not support Latin characters:

![image](https://user-images.githubusercontent.com/6536985/85204071-494a8a00-b2e8-11ea-9cb9-6e46d64a32e7.png)

To find this [font file](https://github.com/React95/React95/blob/master/packages/core/components/shared/assets/font/MS-Sans-Serif.ttf) I did a lot of research but apparently I should have done a better job 😂 

Researching again, I found [some fonts](https://fontsarena.com/w95fa-by-fontsarena/) that seem to be the one used in w95, but it is not quite right (in my opinion). 

So I've decided to find the original and try to add it to the 95. And, good news, I found it! 

But... 

It is in `.fon` file format.

[SERIFF.FON.zip](https://github.com/React95/React95/files/4808038/SERIFF.FON.zip)

This _zip_ file contains the `MSSans` font used in w95. 

Opening this file font in FontForge software, I've discovered that this is a bitmap font, containing different fonts for different sizes: 13px, 17px, 20px, 23px, 30px and 40px). To illustrate the different fonts, I've printed several "@" characters:

![image](https://user-images.githubusercontent.com/6536985/85204344-46e92f80-b2ea-11ea-91e1-d8161409b540.png)

The 13px font seems to be ok for me to add to React95 as the default font (`body`):
![image](https://user-images.githubusercontent.com/6536985/85204422-beb75a00-b2ea-11ea-8a9a-59818d8ca47d.png)

I don't know how to extract it and generate the `.ttf`, `.woff` or `.woff2` file formats to be used inside React95. 

I would appreciate it if someone could help me with this.

**Comment by alan-oliv** [comment]
@ggdaltoso I'd like to help you guys in this one

Do you intend to maintain different `font-family` for each `font-size` like windows95 does, or there's is a specific one that you'd use for all sizes?

**Comment by ggdaltoso** [comment]
Initially, I was thinking in replace the [current font](https://github.com/React95/React95/blob/master/packages/core/components/shared/assets/font/MS-Sans-Serif.ttf) with the one mentioned above. 

Then, we could discuss the idea originally from @andreloureiro of making a Text component whit a property named `size`, for example, giving us something to handle and be able to change the font of this component. 

So, to clarify:

1. Change the default font to the one extracted from `SERIFF.FON.zip` (13px), mentioned earlier.
2. Add the reminiscent fonts: 17px, 20px, 23px, 30px and, 40px, and create a Text component to handle and change which font-family should have its content.

What do you think?

**Comment by alan-oliv** [comment]
Actually, I'd like to go further here. 

Extracting each size of the `bitmap font` to a respective `true type` will lead us to have multiple font files, and thus the only solution is to handle the 5 fonts (17px, 20px, 23px, 30px and, 40px) in the code (Text component)

Instead of doing this, I'd like to propose a creation of our own open-source font (React95.ttf) and treat the size difference behaviour on the font creation itself, leading us to have a unique font file. 

IMO let the responsibility to the font handle it's own differences on each size by design, sounds like a cleaner solution to me 
I'll have to go deeper on this, but I'm almost sure I can do it

How you guys feel about that?

**Comment by ggdaltoso** [comment]
It would be awesome!

But, I don't know how to do that. Do you know?

**Comment by ggdaltoso** [comment]
There is a very accurate font on [98.css](https://github.com/jdan/98.css) that we could use too...  🤔

**Comment by ggdaltoso** [comment]
It looks like 98.css doesn't have support for Latin characters either. 

I'm almost closing this issue... 😞

**Comment by ggdaltoso** [comment]
I finally was able to fix this issue! 🎉 

I created a PR that updates the main font and, in addition to that, there is also a new repository if you want to use a serif font: https://github.com/React95/R95-Sans-serif
