### ISSUE TITLE
Add more contributors to readme section

### ISSUE THREAD

**Issue by allyssonsantos** [React95/React95#159]
Hi!

What do you think to include everyone that had at least one commit to the project in the contributor's section of the readme?

We can add those wonderful developers:

- @InsafKhamzin (doc)
- @LRNZ09 (doc)
- @kaiofelipejs (doc)
- @ddsilva (test)
- @DanielRosenwasser (doc, code, test)
- @mikegsrv (code, test)
- @anton-g (code)
- @accuvit (code)
- @thomazcapra (code, test)
- @beizhedenglong (code)
- @luizcieslak (doc, ideas)
- @oddisland (code)
- @lukehorvat (doc)

**Comment by ggdaltoso** [comment]
Of course!

**Comment by ggdaltoso** [comment]
Done!
