### ISSUE TITLE
Unable to view icon storybook

### ISSUE THREAD

**Issue by theoomoregbee** [React95/React95#175]
![Screen Shot 2020-08-17 at 10 43 09 AM](https://user-images.githubusercontent.com/10440327/90408867-73b18d00-e076-11ea-96f7-c4e3ba35e58b.png)

**Comment by ggdaltoso** [comment]
Hi @theoomoregbee!

Thanks for opening this issue!

I'm working on add TS support, in #174, and I will probably solve the icons problem in this opened PR.

But, if you want to contribute with this issue for now, since I may take some time on TS stuff, I could help you with it.  

What do you think?

**Comment by theoomoregbee** [comment]
Cool! I can send in a PR for it later today

**Comment by theoomoregbee** [comment]
@ggdaltoso here's a quick PR fix for it https://github.com/React95/React95/pull/176
