### ISSUE TITLE
react95/core package import all icons and weight up the bundle size

### ISSUE THREAD

**Issue by kaiofelipejs** [React95/React95#189]
Hi everyone! 

I analyzed the [lighthouse report](https://web.dev/) from [my site](https://kaiofelipejs.dev/) and the performance score is below 60 points. He is created with Gatsby (using React5, obviously) and performance is the focus in this framework. I found it strange.

Looking at the principal recommendation by the lighthouse "Remove unused Javascript" I see that one of the files unused is the icons [(click here to see minified)](https://kaiofelipejs.dev/63143b0cbae5c49cf7d25a096ffe49c9e5eb8977-7ed00e3126f6ce37baf1.js).

To understand more, I installed an analyzer and confirm this:
![image](https://user-images.githubusercontent.com/41922744/97220611-7cc38680-17aa-11eb-8f74-c773c1d14cf1.png)

All icons are imported, even if they are not used. This weighs + 1.2Mb 😱

How we can optimize this issue?

Tell me if u need more information :)

**Comment by ggdaltoso** [comment]
Hi, @kaiofelipejs !

First of all, I want to say sorry for the delay in this issue. 

I've rewritten the `@react95/icons` package as a simple CSS file, meaning also that we can use it despite React though.

Could you, please, redo your analysis with the last version (v2.13.3) of the @react95/core?

I've got great results when I tested into my [95Recipes](https://github.com/ggdaltoso/95Recipes) and I hope I can get it too as well.

**Comment by kaiofelipejs** [comment]
Hi, @ggdaltoso!

I updated the package and fix the names of the icons (because the broken contract, this update should be major, right? maybe 3.0). 

I test [my site](htttps://kaiofelipejs.dev) but the results are the same :|
I test 95Recipes to and have this warning: 
![image](https://user-images.githubusercontent.com/41922744/103939681-eb0db900-510a-11eb-8eff-48c4f6537e8e.png)
File mentioned: https://ggdaltoso.dev/95Recipes/static/css/2.b198e031.chunk.css

It seems to me that the problem persists :(

**Comment by ggdaltoso** [comment]
@kaiofelipejs 

@react95/icons now export each icon as a separated component so it may solve your issue.

Could you check it again, please?

**Comment by kaiofelipejs** [comment]
> @kaiofelipejs
> 
> @react95/icons now export each icon as a separated component so it may solve your issue.
> 
> Could you check it again, please?

Niceeeee!!!!! Congrats bro, this will take the project to next level. 
I update packages in my project, run analyzer and the result is: 

![image 1](https://user-images.githubusercontent.com/41922744/120907163-b0feff80-c635-11eb-8c64-0ac41cf2a0d2.png)

Amazing! Before was +1.2Mb!!!

**Comment by ggdaltoso** [comment]
Nice!

I'll close the issue and if it happens again we could open it again.

Thanks, @kaiofelipejs and @kirkobyte !
