### ISSUE TITLE
Remove unnecessary dependencies and move dev dependencies to devDependencies

### ISSUE THREAD

**Issue by kirkobyte** [React95/React95#242]
Some dependencies like `styled-system/prop-types`, `react-virtualized`, `isomorphic-fetch` and `@types/react-virtualized` don't appear to be used in the project and could be removed.

Others, like `ts-loader`, `icojs` are only used in development of React95 and can be moved to `devDependencies` to make sure consuming apps don't end up with those packages in their `node_modules` when they install React95.

If we tidy these up, it can simplify `node_modules` for users a bit

**Comment by ggdaltoso** [comment]
Seems to be easy to solve and you already describe almost everything we need to do :+1: 

Maybe you could guide someone to help us with this one or we could submit a PR with those changes.

**Comment by kirkobyte** [comment]
Sure thing! If anyone else wants to take a look at this before I get a chance to open a PR:

1. look through all `package.json` files in the project, look for packages in the `dependencies` field that aren't referenced elsewhere in the runtime
    - If they're used in the build tools (e.g. `processIcons.ts` or other build steps), move them to `devDependencies`
    - If they aren't referenced anywhere, delete the line with the dependency
1. Run yarn install to make sure there are no missing peer dependencies
1. Yarn link/yalc install the project in another app to make sure things work as expected

Happy to work through this with anyone also :)
