### ISSUE TITLE
Icons Issue

### ISSUE THREAD

**Issue by claire-scout** [React95/React95#259]
When I try to install react95/icons using command npm install @react95/icons or yarn add @react95/icons, it doesn't seem to install everything necessary. When I try to follow the instructions in the docs of importing the css file `import '@react95/icons/icons.css'`, I get the error `...node_modules/@react95/icons/esm/react/Access110.js
Module not found: Can't resolve '../../png/Access110_16x16_4.png' in '.../node_modules/@react95/icons/esm/react'`

When I look in the @react95/icons file structure i don't see any png folder with pngs in it. 

Any help would be appreciated! A little more documentation on how to use @react95/icons would also be super helpful.

Thank you so much for making this cool library!

**Comment by ggdaltoso** [comment]
Hey, @claire-scout !!! Glad to see you here!

This seems to be a duplicate from #253 and will be solved by #260 🙏 

But, in addition to that, I would like to invite you to build a better doc for @react95/icons. What we have in our current doc, describes what we have to do to consume the icons package as a CSS file but, when we merge #238, we've forgotten to update the description with how to use an Icon as a component itself.

What do you think about joining our contributor's team?
