### ISSUE TITLE
Problems at using the React95 with next.js

### ISSUE THREAD

**Issue by breno-felipe** [React95/React95#296]
Hi, @ggdaltoso 

I'm make my blog using next.js with React95 but some errors was returned.

This error is returned because an invalid token or unexpected token, conform picture below

![image](https://user-images.githubusercontent.com/50807243/142078567-d299736c-f529-4230-a29d-847deb1900e7.png)

I believe the format the image is exported to returns this error, but I'm not sure.

So I'm investigating to see what causes this issue.

**Comment by ggdaltoso** [comment]
Hi, @breno-felipe 

Is this related to #253 in any way?

**Comment by breno-felipe** [comment]
Yes, a solution presented by @earksiinni is what I ended up doing and it worked
