### ISSUE TITLE
Is it okay to use commercial, really?

### ISSUE THREAD

**Issue by cybaj** [React95/React95#313]
I know this project's license is MIT. 
But I worry about that MS wouldn't okay for this.

I have called with MS service center, but received common response with [MS copyright webpage](https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/permissions). They said "call a lawyer".

- Use of Microsoft Copyrighted Content : https://www.microsoft.com/en-us/legal/copyright/permissions 
- Copyright FAQ : https://www.microsoft.com/en-us/legal/intellectualproperty/copyright 
- Microsoft Trademark and Brand Guidelines : https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks 

Is anyone who experienced similar issues, help me please.

**Comment by ggdaltoso** [comment]
It is really a good point 🤔 

I'll try to dig into this and let you know what I found

**Comment by ggdaltoso** [comment]
Maybe @grassmunk can help here a little bit?

**Comment by ggdaltoso** [comment]
Hey, @cybaj 

After talking with some specialists about it, the solution for this is quite simple: we just need to add this sentence

> Windows and all associated images are the property of the Microsoft Corp and are not covered by this license

at the top of our license file. It would be nice to have this message somewhere in the README as well.

So, do you want to contribute?

**Comment by cybaj** [comment]
@ggdaltoso Okay, thank you for the answer and contribution suggestion. I will contribute it.

**Comment by ggdaltoso** [comment]
closed by #318

**Comment by ggdaltoso** [comment]
closed by #318
