### ISSUE TITLE
CDN's for clippy are down

### ISSUE THREAD

**Issue by Mrpanquecas** [React95/React95#319]
Can't reach the CDN's for clippy over at 

https://gitcdn.xyz/repo/pi0/clippyjs/master/assets/agents/Clippy/agent.js

and

https://gitcdn.xyz/repo/pi0/clippyjs/master/assets/agents/Clippy/sounds-mp3.js

**Comment by ggdaltoso** [comment]
🤔 

It is probably related to [this commit](https://github.com/React95/React95/commit/a8b861f863eb95a57d2cb972902b3a35f0e1bed2) which comes as solution for #218 

So, it looks like `gitcdn` isn't the best provider. Although it is faster, sometimes it comes down (don't know why).
We can rollback this changes but need to check window conditionally before setting this new env variable.
Easy fix, I guess.

I'd love to have your contribution on this, @Mrpanquecas. What do you think?

**Comment by Mrpanquecas** [comment]
Do I need specific permissions to contribute? @ggdaltoso

**Comment by ggdaltoso** [comment]
You shouldn't!

Just fork the project and make sure to follow our contribution guidelines

**Comment by Mrpanquecas** [comment]
I created [this pr](https://github.com/React95/React95/pull/321) but I don't really know how to test clippy locally on story book :)

**Comment by ggdaltoso** [comment]
Yes, it does!

As soon as this code runs in the server, it would get into the falsy condition. When the code reaches the browser, the window will be available and the CDN will be changed. 

Clippy will work only on the client side and not in the server side so, your solution will work as expected (I hope 😂)

We might need something better to test Clippy, you're right. Maybe we can get a CRA into its package, just to run and test the Clippy. Would you like to contribute one more time?
