### ISSUE TITLE
input and textfield have rounded corners on iOS

### ISSUE THREAD

**Issue by chadlavi** [React95/React95#335]
I think they just need `-webkit-appearance: none;` in their CSS.

**Comment by ggdaltoso** [comment]
Would you like to contribute?

**Comment by ggdaltoso** [comment]
Hey, @chadlavi!

You should have your issue fixed on [@react95/core@6.0.2](https://www.npmjs.com/package/@react95/core/v/6.0.2) 🎉 

Thanks for opening it and feel free to open more!
Thanks for the effort also, @mavericardo 💪
