### ISSUE TITLE
theme.colors is undefined in TitleBarBackground in TitleBar.js

### ISSUE THREAD

**Issue by jabusir** [React95/React95#377]
This bug occurred while trying to use the 'Video' component. I copied and pasted from the storybook exactly, and then got an error saying that "@xstyled/styled-components" was not found so I added that to the dependencies and installed using yarn. 

Then I got the error saying that 'theme.colors is undefined'.

I've replicated the bug in a codesandbox. 
https://codesandbox.io/s/sharp-artem-o3jxsz?file=/src/App.js

**Comment by ggdaltoso** [comment]
Hi, @jabusir! Thanks for using React95 and for opening this issue.

You need to wrap your application with `ThemeProvider` to get used to all its variables.
I forked your example and got it running by following what I just said
https://codesandbox.io/s/mystifying-swartz-xz4bhn

I'm closing this issue for now, but we can always reopen it if it happens again

**Comment by ggdaltoso** [comment]
It is currently on [@react95/core README file](https://github.com/React95/React95/tree/master/packages/core#usage)

A little out of date but the information you are looking for is there.
Let me know if you have any idea to make it better. 

I hope to get a contribution of yours!
