### ISSUE TITLE
can not use in latest nextjs (13.4.19)

### ISSUE THREAD

**Issue by zerosoul** [React95/React95#407]
I have done based on the intro: https://github.com/React95/React95/tree/master/packages/core#nextjs

and add some code for styled-components based on this: https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-components

at last error this: 
<img width="626" alt="image" src="https://github.com/React95/React95/assets/2985895/71dcab96-238a-4777-b068-22fa0854ee97">

styled-component version problem? nextjs support v6, but react95 v5 ?

**Comment by zerosoul** [comment]
oh  I don't use the `next-transpile-modules` because nextjs natively support it with `transpilePackages: ["@react95/core", "@react95/icons"]` setting

**Comment by ggdaltoso** [comment]
Sorry for the delay in the reply here, @zerosoul

I also have no clue but I'll try to figure it out and update the template we have. Thanks for letting me know about this issue

**Comment by AlfieDarko** [comment]
also facing this issue, was trying to figure out if something with the transpile settings could be changed but no luck

**Comment by ggdaltoso** [comment]
@AlfieDarko @zerosoul Can you, please, check if v8.0.2 fixed this issue too?

More details in #449 and #445
