### ISSUE TITLE
Video player throws onChange handler error in React 18 Vite

### ISSUE THREAD

**Issue by snivets** [React95/React95#409]
Hey - new to React. Trying to use the Video component exactly as is used in Storybook in a new React 18 Vite project, and run across this error: Warning: You provided a valueprop to a form field without anonChangehandler. This will render a read-only field. If the field should be mutable usedefaultValue. Otherwise, set either onChangeorreadOnly.. What is going on under the hood here?

The code is the following:
<Video w="320" src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4" style={{
marginBottom: 4
}} />

Turns out I posted this in the wrong React95 Github previously. 👱

**Comment by ggdaltoso** [comment]
Hey, @snivets! 
Sorry for my late reply 🕊️ 

I was able to reproduce your issue: https://stackblitz.com/~/edit/vitejs-vite-ztemec?terminal=dev
and I already know how to fix it.

Would you like to contribute or can I fix it for you?

**Comment by snivets** [comment]
I'd love it if you did! 🤠

**Comment by ggdaltoso** [comment]
Hey, @snivets!

This issue was fixed and shipped with [@react95/core v7.0.2](http://npmjs.com/package/@react95/core) 🎉 

I updated the [StackBlitz link](https://stackblitz.com/~/edit/vitejs-vite-ztemec) for you to see

Thanks for noticing it and let me know if you need any more help!
