### ISSUE TITLE
Theme doesn't seem to apply to taskbar

### ISSUE THREAD

**Issue by quinn** [React95/React95#427]
I have not used this library, I was just observing this while looking through the storybook:

https://react95.github.io/React95/?path=/story/taskbar--simple&globals=selectedTheme:highContrast;backgrounds.grid:!false

Here's what I see:

![image](https://github.com/React95/React95/assets/3764/5976c1ba-7a3e-46c4-a7d3-86a5e1ce5282)

**Comment by quinn** [comment]
to be specific, it doesn't apply to the taskbar foreground color.

**Comment by ggdaltoso** [comment]
Hey, @quinn! Thanks for letting me know about this issue!

I'm working on a big refactor, and your warning is on time!

I'll keep this issue open and I hope it will be closed when #425 is merged.
