### ISSUE TITLE
Storybook failing

### ISSUE THREAD

**Issue by ghazian** [React95/React95#432]
Not much to add on this issue, link on the storybook is failing.

Example link:
https://react95.github.io/React95/?path=/docs/range--docs

![Screenshot 2024-03-29 at 15 46 23](https://github.com/React95/React95/assets/51567361/7b0f71c0-6f60-4259-81ce-76be284a2b14)

**Comment by ggdaltoso** [comment]
I'm working on it!

Thanks for flagging it!

**Comment by ggdaltoso** [comment]
The Storybook is now back online again!

https://react95.github.io/React95/?path=/story/all--all
