### ISSUE TITLE
Modals cannot get focused and will not appear in TaskBar.

### ISSUE THREAD

**Issue by izwb003** [React95/React95#444]
Hello,
First I want to say that this project is really amazing and is pretty interesting for old-school UI lovers like me! Thank you for your hard work!

But here I consider I met a problem in the latest 8.0.0 version. After I create a Modal, it cannot get focused. The title bar just keeps grey and does not appear at the TaskBar, even after clicking it with the mouse. Like this:
![屏幕截图 2024-07-17 210602](https://github.com/user-attachments/assets/e467b3e3-d480-4582-8a94-eb1f5a556d3f)

I consider it is a bug because I tried to reverse to version 7.0.2 and everything works fine. However I'm not sure whether I made a mistake or not, as I'm not really familiar with programming in React and even JavaScript. So can you take a look at that?

Many thanks!

**Comment by ggdaltoso** [comment]
Hey, @izwb003! Thanks for submitting this issue!

Could you, please, submit a reproducible repo?

**Comment by izwb003** [comment]
> Hey, @izwb003! Thanks for submitting this issue!
> 
> Could you, please, submit a reproducible repo?

Is it possible to describe it? Just take the example project on [StackBlitz](https://stackblitz.com/edit/react95-vite-starter?file=README.md) as an example:

In ```src/App.tsx```, just add this modal:
![屏幕截图 2024-07-19 022046](https://github.com/user-attachments/assets/cb2ab4f3-e36a-4470-b75d-45be8a8cf3bd)
Then it happens.

I've tried to add/delete attributes, fill something in it or set styles, but it keeps happen - cannot get focused. But creating a modal with the same method in 7.0.2, everything works fine:
![image](https://github.com/user-attachments/assets/b3815513-678b-415a-973a-b8cfba7f24c5)

(Did not forget to init React95 with ```GlobalStyle```, ```ThemeProvider``` in ```main.tsx```, yeah.)
Any idea about this? Thanks!

**Comment by ggdaltoso** [comment]
Ooo I see why:
It is missing the `ModalContext`, previously shipped within GlobalStyle, if I remember well.

If you add the `ModalContext`, surrounding your application, you'll notice the taskbar being populated and the modal being able to be activated as well.

You may notice a modal being added to the taskbar twice. This might happen if you are in dev mode and it should not happen otherwise. 

Can you check if this works for you?

**Comment by izwb003** [comment]
> Ooo I see why: It is missing the `ModalContext`, previously shipped within GlobalStyle, if I remember well.
> 
> If you add the `ModalContext`, surrounding your application, you'll notice the taskbar being populated and the modal being able to be activated as well.
> 
> You may notice a modal being added to the taskbar twice. This might happen if you are in dev mode and it should not happen otherwise.
> 
> Can you check if this works for you?

Do you mean I have to do this to render this app?
```js
ReactDOM.createRoot(document.getElementById('root')).render(
    <ModalProvider>
        <App />
    </ModalProvider>,
);
```
I tried this and it runs properly, thank you very much!

It's my suggestion to note this in ```/packages/core/README.md``` or in the StoryBook because I believe someone else may make the same mistake as I made...

**Comment by izwb003** [comment]
Also, is it possible for me to know, if you have time...

1. Is it possible to show the Maximize or Minimize button in a modal's titlebar? As I see, the titlebar only shows the close and the help button, but I can see those svgs of Maximize and Minimize in the source code, so can we do something to show these buttons? I cannot find helpful information from the StoryBook.

2. Is it possible to add CSS rules to a Modal with ```styled-components``` ? I tried this to make a modal maximized in 8.0.0 and failed, but working in 7.0.2:
```js
export const FullscreenModal = styled(Modal)`
    top: 0;
    height: calc(100% - ${TASKBAR_HEIGHT}px);
    width: 100%;
`;
```
Any idea about this? I can see it once being discussed in #283 , but I didn't get it well...

**Comment by ggdaltoso** [comment]
We moved from `styled-components` to `vanilla-extract` so the syntax is slightly different.

It sounds good to me but even better if we could have your contribution on this! What do you think?
It seems you already looked at the code and are familiar with it. It is an easy task for you.

**Comment by izwb003** [comment]
> We moved from `styled-components` to `vanilla-extract` so the syntax is slightly different.

Clear about that! I will try to learn more about this.

> It sounds good to me but even better if we could have your contribution on this! What do you think? It seems you already looked at the code and are familiar with it. It is an easy task for you.

I am not very familiar with React and JavaScript, but I am interested in giving it a try! I may try to make some modifications and submit a PR, if I have free time.

I will make this issue closed then. Thank you again for these great ideas!
