### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by nekwo** [React95/React95#451]
Haven't really worked with vanilla extract, not sure how to override the themes/styles without forking the package? 
Same with the global styles a bit confused about that. 
Trying to get a similar vibe to the game needy streamer overload. 

coming back from cpp to js/tsx after a long while i want to cry lol

**Comment by ggdaltoso** [comment]
Right now we don't expose any way to create/generate a theme but it shouldn't be that hard.

There are a couple of properties we expose on our themes that can be overwritten by a plain global CSS file, such as:

```css
:root {
  --r95-zIndex-modal: 2;
  --r95-zIndex-tooltip: 3;
  --r95-zIndex-taskbar: 3;
  --r95-space-0: 0px;
  --r95-space-1: 1px;
  --r95-space-2: 2px;
  --r95-space-3: 3px;
  --r95-space-4: 4px;
  --r95-space-5: 5px;
  --r95-space-6: 6px;
  --r95-space-7: 7px;
  --r95-space-8: 8px;
  --r95-space-9: 9px;
  --r95-space-10: 10px;
  --r95-space-11: 11px;
  --r95-space-12: 12px;
  --r95-space-13: 13px;
  --r95-space-14: 14px;
  --r95-space-15: 15px;
  --r95-space-16: 16px;
  --r95-space-17: 17px;
  --r95-space-18: 18px;
  --r95-space-19: 19px;
  --r95-space-20: 20px;
  --r95-color-anchor: #000e7a;
  --r95-color-anchorVisited: #440381;
  --r95-color-borderDark: #868a8e;
  --r95-color-borderDarkest: #000000;
  --r95-color-borderLight: #d2d2d2;
  --r95-color-borderLighter: #e6e6e6;
  --r95-color-borderLightest: #ffffff;
  --r95-color-canvas: #000000;
  --r95-color-canvasText: #ffffff;
  --r95-color-headerBackground: #000e7a;
  --r95-color-headerNotActiveBackground: #7f787f;
  --r95-color-headerNotActiveText: #c6c6c6;
  --r95-color-headerText: #fefefe;
  --r95-color-material: #c3c7cb;
  --r95-color-materialText: #000000;
  --r95-color-materialTextDisabled: #868a8e;
  --r95-color-materialTextDisabledShadow: #d2d2d2;
  --r95-color-materialTextInvert: #ffffff;
  --r95-color-progress: #000e7a;
  --r95-color-inputBackground: #ffffff;
  --r95-color-inputBackgroundDisabled: #d2d2d2;
  --r95-shadow-out: inset 0.5px 0.5px 0px 0.5px #ffffff,
          inset 0 0 0 1px #868a8e,
          1px 0px 0 0px #000000,
          0px 1px 0 0px #000000,
          1px 1px 0 0px #000000;
  --r95-shadow-in: inset 0px 0px 0px 0px,
        inset 1px 1px 0px 0px #868a8e,
        0.5px 0.5px 0px 0.5px #ffffff;
  --r95-shadow-input: inset -1px -1px 0 0 #c3c7cb,
            inset 1px 1px 0 0 #000000,
            0.5px 0.5px 0 0.5px #ffffff;
}
```

more details/properties you can override, in the code itself:
 1. Go to https://www.npmjs.com/package/@react95/core?activeTab=code
 2. navigate to the themes assets folder: `/@react95/core/esm/themes/*.css.ts.vanilla.css`
 3. And, if you want to, on GlobalStyles too: `@react95/core/esm/GlobalStyle/GlobalStyle.css.ts.vanilla.css`

If you want to contribute to exposing our contracts or adding docs on how to override our themes, feel free to open a PR. 
I'll be more than glad to help you with it.

Thanks for creating this issue, btw <3

**Comment by nekwo** [comment]
Thank you for telling me where to look and for the quick reply, I'm starting to get the hang of it, Most Things are well exposed I just had to be a little hacky with the taskbar to have it's own color independent from the global $material variable

.r95_iuzg8937 {
  background-color: #adbfc1; /*task bar time block color*/
}

.r95_iuzg892l {
  background-color: #adbfc1; /*task bar color*/
}

.r95_iuzg893d {
  background-color: #adbdc4; /*task bar border block color*/
}

.r95_1ct83mo2{
  background-color: #adbdc4; /*start button color*/
}

More Importantly I wanted to do a few things with the modal https://react95.github.io/React95/?path=/docs/modal--docs
-increase the border thickness 
-add a background Image to it
-and change the X button image, 

I see the first two are possible already in the docs but it doesn't seem to change for me at all when I 

`{showModal && <Modal borderImage="url(x.jpg)" width="300px" height="200px" icon={<Computer variant="16x16_4" />}`

**Comment by ggdaltoso** [comment]
@nekwo since v9.0.0, Modals can now receive the `className` prop so you can style it the way you want!

You can now make use of the new Modal API, to create more robust components (see #462)

![image](https://github.com/user-attachments/assets/47088eeb-95c0-4ecb-acc8-847dca4bc1ab)

```jsx
import { Button, List, TitleBar, Modal  } from "@react95/core";
import { Computer } from "@react95/icons";

<Modal
  icon={<Computer variant="16x16_4" />}
  title="Browse"
  dragOptions={{
    defaultPosition: {
      x: 0,
      y: 20,
    },
  }}
  titleBarOptions={[
    <TitleBar.Help
      key="help"
      onClick={() => {
        alert('Help!');
      }}
    />,
    <TitleBar.Close key="close" onClick={handleCloseModal} />,
  ]}
  buttons={[
    { value: 'Ok', onClick: handleButtonClick },
    { value: 'Cancel', onClick: handleButtonClick },
  ]}
  menu={[
    {
      name: 'File',
      list: (
        <List width="200px">
          <List.Item onClick={handleCloseModal}>Exit</List.Item>
        </List>
      ),
    },
    {
      name: 'Edit',
      list: (
        <List width="200px">
          <List.Item>Copy</List.Item>
        </List>
      ),
    },
  ]}
>
  <Modal.Content
    width="300px"
    height="160px"
    boxShadow="$in"
    bgColor="white"
  >
    Simple modal
  </Modal.Content>
</Modal>
```

If you are ok with it and this new API fits your needs, please, consider closing this issue. 

Thanks for raising this question, btw!

**Comment by nekwo** [comment]
Really good stuff, overrode some hardcoded styles in the Title bar to make it bigger not sure if there was an api for that but other than that it's alot nicer to work with ty

.r95_1kpzw682 {
  box-shadow: inset 0px 0px 0px 1px #212323, /* Border line */
              0px 1px 2px rgba(0, 0, 0, 0.2); /* Hovering effect */
  padding: 7px;
  padding-bottom: 22px;
}
