### ISSUE TITLE
Close button on modals has problems on mobile devices

### ISSUE THREAD

**Issue by abel8000000** [React95/React95#454]
The hitbox of the close button on modals gets all weird when using touch controls. In the video attached you can see what i'm talking about. It looks like the touch area is above the actual button.
I think something similar happens with the titlebar, you can only drag the window if you touch the upper half of the titlebar, but this is less noticeable.

https://github.com/user-attachments/assets/add9ab2b-fb36-4864-a0eb-0af6de7e0283

**Comment by ggdaltoso** [comment]
I'm going to refactor the Modal and you can be sure I'm going to address this. In the meantime, do you have a suggestion on how to fix this?

**Comment by ggdaltoso** [comment]
Hi, @abel8000000 

Could you, please, try to reproduce it with `@react/core` v9.0.0? I think I might fixed this issue along with some other features in #462

**Comment by abel8000000** [comment]
The problem is now fixed, thanks for your help.
