### ISSUE TITLE
Issue building project using the latest version of React95

### ISSUE THREAD

**Issue by simlf** [React95/React95#476]
Hello,

At first thanks a lot for your package !

I don't have any issue running my project locally (`npm run dev`).

However, when I try to building it (`npm run build`)

I have this issue :

```
Failed to compile.
./node_modules/react95/dist/common/hooks/useIsFocusVisible.mjs
Attempted import error: 'findDOMNode' is not exported from 'react-dom' (imported as 'findDOMNode').

Import trace for requested module:
./node_modules/react95/dist/common/hooks/useIsFocusVisible.mjs
./node_modules/react95/dist/Slider/Slider.mjs
./node_modules/react95/dist/index.mjs
./app/components/layout/Windows95Browser.tsx
./app/components/Layout.tsx
./app/page.tsx
```

For more context, I am using `Next.js 15.0.2` along with `React 18`
Do you have an idea of why this occurs ?

I use the latest version of React95 by the way.

**Comment by hlee-bc** [comment]
Hi, may I know if this was fixed?
