### ISSUE TITLE
Create build process and publish

### ISSUE THREAD

**Issue by allyssonsantos** [React95/React95#57]
We need to make a build process to generate dist files.
Can be one of the main bundler tools like Webpack, Rollup or just transpiling with Babel.

What approach do you think we can take?

After that we need to publish React95 to NPM.

**Comment by ggdaltoso** [comment]
I will work on this!

I spend a lot of time studying Webpack, Rollup and babel and I think I reach an conclusion.

Could you keep tracking this issue in that [branch](https://github.com/React95/React95/tree/%2357-build)?

And, of course, we will still discuss about it
