### ISSUE TITLE
Tree view component

### ISSUE THREAD

**Issue by allyssonsantos** [React95/React95#68]
We need to implement Tree view component:

![image](https://user-images.githubusercontent.com/13424727/53165081-8e559380-35b0-11e9-8e22-8e63b21fa53f.png)

**Comment by andreloureiro** [comment]
Hey @allyssonsantos! I assume @ggdaltoso talked to you about me picking up this task, I'm up for working on this component if you don't mind :)

**Comment by allyssonsantos** [comment]
Hi @andreloureiro, don't worry, you can take this one. :smiley:

**Comment by allyssonsantos** [comment]
Hi @andreloureiro, how are you?

Do you have any updates with the development of this component?

**Comment by andreloureiro** [comment]
Hey @allyssonsantos sorry for the delay, lots of real-life stuff going on and I was rushing with some other stuff during the last month. Anyway, there it goes https://github.com/React95/React95/pull/97
