### ISSUE TITLE
How to handle with assets files in the build process

### ISSUE THREAD

**Issue by allyssonsantos** [React95/React95#95]
We already discussed this topic, but, I think that we need to discuss it again :rofl: 

How can we handle the assets files (.ico, .png, .ttf, etc) in the build process?

What is the best approach to delivery this files?

- Should we include this on the bundle? With webpack/rollup/etc?
- Should we keep the way it is? the generated code will import the static files "as it is", and the application that will consume React95 needs to handle this imports?

With the first approach we will increase our bundle size considerably, because we have a several static files.

With the second approach the application that will use React95 will need to configure its bundler tool to handle with that files, if not, the application will throw an error.

What do you think? @ggdaltoso

**Comment by padraigfl** [comment]
RE: TTF, is there any reason for including it? When even IE9 supports WOFF you're probably in the clear!

Imo it's down to whether you want the library to be one that people use (i.e. easily started) or if it's more about learning how to build a library efficiently. As it's likely to be used only for recreational purposes, the bundle size seems far less important than ease of use to me.

**Comment by ggdaltoso** [comment]
Closing this issue for now, since we consider [notifying](https://github.com/React95/React95/tree/master/packages/icons#important) who is using this library to use the loader if it is needed.
